/*---------------------------------------------------------------------------*\

  sc_modem.c

  Single-carrier BBFM modem implementation.

  Reference: radae/dsp.py class single_carrier

\*---------------------------------------------------------------------------*/

/*
  Copyright (C) 2024 David Rowe

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions
  are met:

  - Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.

  - Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
  ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
  A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR
  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#include "sc_modem.h"
#include <stdlib.h>
#include <string.h>
#include <math.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/*---------------------------------------------------------------------------*\
                           Complex arithmetic
\*---------------------------------------------------------------------------*/

typedef struct { float real; float imag; } sc_comp;

static inline sc_comp sc_cmplx(float re, float im) {
    sc_comp c; c.real = re; c.imag = im; return c;
}

static inline sc_comp sc_cmul(sc_comp a, sc_comp b) {
    sc_comp c;
    c.real = a.real * b.real - a.imag * b.imag;
    c.imag = a.real * b.imag + a.imag * b.real;
    return c;
}

static inline sc_comp sc_cadd(sc_comp a, sc_comp b) {
    sc_comp c; c.real = a.real + b.real; c.imag = a.imag + b.imag; return c;
}

static inline sc_comp sc_cconj(sc_comp a) {
    sc_comp c; c.real = a.real; c.imag = -a.imag; return c;
}

static inline float sc_cabs(sc_comp a) {
    return sqrtf(a.real * a.real + a.imag * a.imag);
}

static inline float sc_cabs2(sc_comp a) {
    return a.real * a.real + a.imag * a.imag;
}

static inline float sc_cangle(sc_comp a) {
    return atan2f(a.imag, a.real);
}

static inline sc_comp sc_cexp(float theta) {
    sc_comp c; c.real = cosf(theta); c.imag = sinf(theta); return c;
}

static inline sc_comp sc_cscale(sc_comp a, float s) {
    sc_comp c; c.real = a.real * s; c.imag = a.imag * s; return c;
}

/*---------------------------------------------------------------------------*\
                           Hardcoded constants
\*---------------------------------------------------------------------------*/

/* RRC filter coefficients: alpha=0.25, Nsym=6, M=4, Ntap=24
   Generated by: gen_rn_coeffs(0.25, 1/9600, 2400, 6, 4) */
static const float sc_rrc[SC_NTAP] = {
    -1.6930256626e-02f,
    -7.3022731931e-03f,
     1.6020521058e-02f,
     3.0870277861e-02f,
     1.8991360440e-02f,
    -1.5323695105e-02f,
    -4.8002554634e-02f,
    -5.2360755255e-02f,
    -1.4128956960e-02f,
     6.2729344742e-02f,
     1.5664293185e-01f,
     2.3443012550e-01f,
     2.6470991725e-01f,
     2.3443012550e-01f,
     1.5664293185e-01f,
     6.2729344742e-02f,
    -1.4128956960e-02f,
    -5.2360755255e-02f,
    -4.8002554634e-02f,
    -1.5323695105e-02f,
     1.8991360440e-02f,
     3.0870277861e-02f,
     1.6020521058e-02f,
    -7.3022731931e-03f,
};

/* P25 frame sync word (first 16 of 24) */
static const float sc_sync_word[SC_NSYNC] = {
    1, 1, 1, 1, 1, -1, 1, 1, -1, -1, 1, 1, -1, -1, -1, -1
};

/* p_scale = dot(p,p) / sqrt(dot(p,p)) = 16/4 = 4 */
#define SC_P_SCALE 4.0f

/* LO angular frequency step: exp(j * 2*pi*fcentre/Fs) */
static sc_comp sc_lo_omega(void) {
    return sc_cexp(2.0f * (float)M_PI * SC_FCENTRE / SC_FS);
}

/* RX filter output buffer length: (Nframe+2)*M for timing margin */
#define SC_RX_FILT_OUT_LEN ((SC_NFRAME + 2) * SC_M)

/* Nominal sample point for timing */
#define SC_SAMPLE_POINT 5

/*---------------------------------------------------------------------------*\
                           TX state and implementation
\*---------------------------------------------------------------------------*/

struct sc_modem_tx {
    sc_comp filt_mem[SC_NTAP];      /* FIR filter memory */
    sc_comp lo_phase;               /* LO phase (rectangular) */
};

sc_modem_tx *sc_tx_create(void) {
    sc_modem_tx *tx = calloc(1, sizeof(sc_modem_tx));
    if (!tx) return NULL;
    tx->lo_phase = sc_cmplx(1.0f, 0.0f);
    return tx;
}

void sc_tx_destroy(sc_modem_tx *tx) {
    free(tx);
}

int sc_tx_process(sc_modem_tx *tx, int16_t out[], const float symbols_in[]) {
    int i, j;
    sc_comp lo_step = sc_lo_omega();

    /* Build filter input: [filt_mem | symbol-inserted zeros] */
    int filt_in_len = SC_NTAP + SC_NFRAME * SC_M;
    sc_comp filt_in[SC_NTAP + SC_NFRAME * SC_M];

    /* Copy filter memory */
    memcpy(filt_in, tx->filt_mem, SC_NTAP * sizeof(sc_comp));

    /* Zero-fill the new portion */
    memset(&filt_in[SC_NTAP], 0, SC_NFRAME * SC_M * sizeof(sc_comp));

    /* Insert sync word symbols at interval M, scaled by M */
    for (i = 0; i < SC_NSYNC; i++) {
        filt_in[SC_NTAP + i * SC_M].real = sc_sync_word[i] * SC_M;
    }

    /* Insert payload symbols at interval M, scaled by M */
    for (i = 0; i < SC_NPAYLOAD; i++) {
        filt_in[SC_NTAP + (SC_NSYNC + i) * SC_M].real = symbols_in[i] * SC_M;
    }

    /* FIR convolution: out[i] = dot(filt_in[i+1 .. i+Ntap], rrc) */
    sc_comp tx_filt_out[SC_NSAMPLES];
    for (i = 0; i < SC_NSAMPLES; i++) {
        float re = 0.0f, im = 0.0f;
        for (j = 0; j < SC_NTAP; j++) {
            re += filt_in[i + 1 + j].real * sc_rrc[j];
            im += filt_in[i + 1 + j].imag * sc_rrc[j];
        }
        tx_filt_out[i].real = re;
        tx_filt_out[i].imag = im;
    }

    /* Save filter memory (last Ntap samples of filt_in) */
    memcpy(tx->filt_mem, &filt_in[filt_in_len - SC_NTAP], SC_NTAP * sizeof(sc_comp));

    /* Frequency shift to centre frequency and output */
    for (i = 0; i < SC_NSAMPLES; i++) {
        sc_comp shifted = sc_cmul(tx_filt_out[i], tx->lo_phase);
        tx->lo_phase = sc_cmul(tx->lo_phase, lo_step);

        /* Take real part, scale, clamp to int16 */
        float sample = shifted.real * SC_TX_SCALE;
        if (sample > 32767.0f) sample = 32767.0f;
        if (sample < -32768.0f) sample = -32768.0f;
        out[i] = (int16_t)sample;
    }

    /* Normalize LO to prevent drift */
    float mag = sc_cabs(tx->lo_phase);
    tx->lo_phase = sc_cscale(tx->lo_phase, 1.0f / mag);

    return SC_NSAMPLES;
}

/*---------------------------------------------------------------------------*\
                           RX state and implementation
\*---------------------------------------------------------------------------*/

/* Sync state */
#define SC_STATE_SEARCH 0
#define SC_STATE_SYNC   1

struct sc_modem_rx {
    /* Filter state */
    sc_comp filt_mem[SC_NTAP];
    sc_comp filt_out[SC_RX_FILT_OUT_LEN];

    /* LO */
    sc_comp lo_phase;

    /* Timing */
    int sample_point;
    int nin;
    float norm_rx_timing;

    /* Phase estimator */
    sc_comp phase_est_mem[SC_NPHASE];
    float phase_est_fine;
    float phase_est_coarse;

    /* Symbol buffer (2 frames for sync search) */
    sc_comp symb_buf[2 * SC_NFRAME];

    /* Sync state machine */
    int state;
    int fs_s;           /* Frame sync position in symb_buf */
    int bad_fs;         /* Consecutive bad frame counter */
    float phase_ambiguity;  /* 0 or pi */
    float g;            /* Amplitude gain */
};

sc_modem_rx *sc_rx_create(void) {
    sc_modem_rx *rx = calloc(1, sizeof(sc_modem_rx));
    if (!rx) return NULL;
    rx->lo_phase = sc_cmplx(1.0f, 0.0f);
    rx->sample_point = SC_SAMPLE_POINT;
    rx->nin = SC_NSAMPLES;
    rx->state = SC_STATE_SEARCH;
    rx->g = 1.0f;
    return rx;
}

void sc_rx_destroy(sc_modem_rx *rx) {
    free(rx);
}

int sc_rx_nin(sc_modem_rx *rx) {
    return rx->nin;
}

int sc_rx_sync(sc_modem_rx *rx) {
    return rx->state == SC_STATE_SYNC;
}

/* Estimate timing and decimate filtered samples to symbols */
static void est_timing_and_decimate(sc_modem_rx *rx, sc_comp rx_symbols[]) {
    int M = SC_M;
    int i;

    /* Compute envelope from sample_point onwards */
    int env_start = rx->sample_point;
    int env_len = SC_RX_FILT_OUT_LEN - env_start;

    /* Single-point DFT at symbol rate frequency 2*pi/M */
    sc_comp x = sc_cmplx(0.0f, 0.0f);
    for (i = 0; i < env_len; i++) {
        float env = sc_cabs(rx->filt_out[env_start + i]);
        float angle = -2.0f * (float)M_PI * i / M;
        x.real += env * cosf(angle);
        x.imag += env * sinf(angle);
    }

    float norm_rx_timing = sc_cangle(x) / (2.0f * (float)M_PI);
    float rx_timing = norm_rx_timing * M;
    float rx_timing_correction = -rx_timing;

    /* Linear interpolation to resample at optimum point */
    int low_sample = (int)floorf(rx_timing_correction);
    float fract = rx_timing_correction - low_sample;

    for (i = 0; i < SC_NFRAME; i++) {
        int idx = rx->sample_point + low_sample + i * M;
        /* Bounds check */
        if (idx < 0) idx = 0;
        if (idx + 1 >= SC_RX_FILT_OUT_LEN) idx = SC_RX_FILT_OUT_LEN - 2;

        sc_comp s0 = rx->filt_out[idx];
        sc_comp s1 = rx->filt_out[idx + 1];
        rx_symbols[i].real = s0.real * (1.0f - fract) + s1.real * fract;
        rx_symbols[i].imag = s0.imag * (1.0f - fract) + s1.imag * fract;
    }

    /* Adjust nin for next frame */
    rx->nin = SC_NSAMPLES;
    if (norm_rx_timing < -0.35f)
        rx->nin += M / 4;
    if (norm_rx_timing > 0.35f)
        rx->nin -= M / 4;

    rx->norm_rx_timing = norm_rx_timing;
}

/* Phase estimation with modulation stripping and coarse/fine tracking */
static void est_phase_and_correct(sc_modem_rx *rx, sc_comp rx_symbs[], int nsymbs) {
    int s, k;

    /* Build symbol buffer: [phase_est_mem | rx_symbs] */
    sc_comp symbol_buf[SC_NPHASE + SC_NFRAME];
    memcpy(symbol_buf, rx->phase_est_mem, SC_NPHASE * sizeof(sc_comp));
    memcpy(&symbol_buf[SC_NPHASE], rx_symbs, nsymbs * sizeof(sc_comp));

    sc_comp corrected[SC_NFRAME];

    for (s = 0; s < nsymbs; s++) {
        /* Modulation stripping: square symbols in window (BPSK, mod_order=2) */
        sc_comp sum = sc_cmplx(0.0f, 0.0f);
        for (k = 0; k < SC_NPHASE; k++) {
            sc_comp sym = symbol_buf[s + 1 + k];
            /* sym^2 for BPSK modulation stripping */
            sc_comp sym2 = sc_cmul(sym, sym);
            sum = sc_cadd(sum, sym2);
        }

        /* Phase estimate (modulo pi for BPSK) */
        float phase_est_fine = sc_cangle(sum) / 2.0f;

        /* Track phase jumps across pi boundaries */
        if (phase_est_fine - rx->phase_est_fine < -0.9f * (float)M_PI)
            rx->phase_est_coarse += (float)M_PI;
        if (phase_est_fine - rx->phase_est_fine > 0.9f * (float)M_PI)
            rx->phase_est_coarse -= (float)M_PI;
        rx->phase_est_fine = phase_est_fine;

        float phase_est = rx->phase_est_coarse + phase_est_fine;

        /* Correct symbol at window centre */
        int centre = s + SC_NPHASE / 2;
        sc_comp correction = sc_cexp(-phase_est);
        corrected[s] = sc_cmul(symbol_buf[centre], correction);
    }

    /* Copy corrected back */
    memcpy(rx_symbs, corrected, nsymbs * sizeof(sc_comp));

    /* Save window tail for next call */
    memcpy(rx->phase_est_mem, &symbol_buf[nsymbs], SC_NPHASE * sizeof(sc_comp));
}

int sc_rx_process(sc_modem_rx *rx, float symbols_out[], const int16_t samples_in[]) {
    int i, j, s;
    int nin = rx->nin;
    sc_comp lo_step_conj = sc_cconj(sc_lo_omega());

    /* Convert int16 to complex and frequency shift to baseband */
    sc_comp rx_bb[SC_NIN_MAX];
    for (i = 0; i < nin; i++) {
        sc_comp sample = sc_cmplx((float)samples_in[i], 0.0f);
        rx_bb[i] = sc_cmul(sample, rx->lo_phase);
        rx->lo_phase = sc_cmul(rx->lo_phase, lo_step_conj);
    }
    /* Normalize LO */
    float mag = sc_cabs(rx->lo_phase);
    rx->lo_phase = sc_cscale(rx->lo_phase, 1.0f / mag);

    /* RRC matched filter */
    int filt_in_len = SC_NTAP + nin;
    sc_comp filt_in[SC_NTAP + SC_NIN_MAX];
    memcpy(filt_in, rx->filt_mem, SC_NTAP * sizeof(sc_comp));
    memcpy(&filt_in[SC_NTAP], rx_bb, nin * sizeof(sc_comp));

    /* Shift old filter output, keep samples we still need */
    int to_keep = SC_RX_FILT_OUT_LEN - nin;
    memmove(rx->filt_out, &rx->filt_out[nin], to_keep * sizeof(sc_comp));

    /* Compute new filtered samples */
    for (i = 0; i < nin; i++) {
        float re = 0.0f, im = 0.0f;
        for (j = 0; j < SC_NTAP; j++) {
            re += filt_in[i + 1 + j].real * sc_rrc[j];
            im += filt_in[i + 1 + j].imag * sc_rrc[j];
        }
        rx->filt_out[to_keep + i].real = re;
        rx->filt_out[to_keep + i].imag = im;
    }

    /* Save filter memory */
    memcpy(rx->filt_mem, &filt_in[filt_in_len - SC_NTAP], SC_NTAP * sizeof(sc_comp));

    /* Timing estimation and decimation to symbol rate */
    sc_comp rx_symbols[SC_NFRAME];
    est_timing_and_decimate(rx, rx_symbols);

    /* Phase estimation and correction */
    est_phase_and_correct(rx, rx_symbols, SC_NFRAME);

    /* Shift symbol buffer and insert new symbols */
    memmove(rx->symb_buf, &rx->symb_buf[SC_NFRAME], SC_NFRAME * sizeof(sc_comp));
    memcpy(&rx->symb_buf[SC_NFRAME], rx_symbols, SC_NFRAME * sizeof(sc_comp));

    /* Sync state machine */
    int next_state = rx->state;
    int fs_s = rx->fs_s;

    if (rx->state == SC_STATE_SEARCH) {
        float max_Cs_abs = 0.0f;
        sc_comp max_Cs = sc_cmplx(0.0f, 0.0f);
        int max_s = 0;

        for (s = 0; s < SC_NFRAME; s++) {
            /* Normalized cross-correlation with sync word */
            sc_comp num = sc_cmplx(0.0f, 0.0f);
            float denom_sq = 0.0f;

            for (i = 0; i < SC_NSYNC; i++) {
                sc_comp rx_sym = rx->symb_buf[s + i];
                /* num += conj(rx_sym) * (sync_word[i] / p_scale) */
                float sw = sc_sync_word[i] / SC_P_SCALE;
                num.real += rx_sym.real * sw;  /* conj(rx)*sw: real*real + imag*imag -> real part */
                num.imag += -rx_sym.imag * sw; /* conj(rx)*sw: -imag*real + real*imag -> but sw is real */
                /* Actually: conj(rx) * sw = (rx.real - j*rx.imag) * sw */
                denom_sq += sc_cabs2(rx_sym);
            }
            /* Fix: conj(rx_sym) * real_value = (rx.real*sw, -rx.imag*sw) */
            /* Already correct above */

            float denom = sqrtf(denom_sq) + 1e-12f;
            sc_comp Cs = sc_cscale(num, 1.0f / denom);
            float Cs_abs = sc_cabs(Cs);

            if (Cs_abs > max_Cs_abs) {
                max_Cs_abs = Cs_abs;
                max_Cs = Cs;
                max_s = s;
            }
        }

        if (max_Cs_abs >= SC_SYNC_THRESH) {
            next_state = SC_STATE_SYNC;
            fs_s = max_s;
            rx->fs_s = fs_s;
            rx->bad_fs = 0;

            /* Resolve phase ambiguity */
            rx->phase_ambiguity = (max_Cs.real < 0.0f) ? (float)M_PI : 0.0f;

            /* Amplitude normalization from sync word */
            float pwr = 0.0f;
            for (i = 0; i < SC_NSYNC; i++) {
                pwr += sc_cabs2(rx->symb_buf[fs_s + i]);
            }
            rx->g = 1.0f / (sqrtf(pwr / SC_NSYNC) + 1e-12f);
        }
    }

    if (rx->state == SC_STATE_SYNC) {
        /* Count errors in sync word */
        sc_comp phase_rot = sc_cexp(rx->phase_ambiguity);
        int n_errors = 0;
        for (i = 0; i < SC_NSYNC; i++) {
            sc_comp sym = sc_cmul(phase_rot, rx->symb_buf[fs_s + i]);
            if (sym.real * sc_sync_word[i] < 0.0f)
                n_errors++;
        }

        if (n_errors > SC_UNSYNC_THRESH1)
            rx->bad_fs++;
        else
            rx->bad_fs = 0;

        if (rx->bad_fs >= SC_UNSYNC_THRESH2)
            next_state = SC_STATE_SEARCH;

        /* Update amplitude normalization */
        float pwr = 0.0f;
        for (i = 0; i < SC_NSYNC; i++) {
            pwr += sc_cabs2(rx->symb_buf[fs_s + i]);
        }
        rx->g = 1.0f / (sqrtf(pwr / SC_NSYNC) + 1e-12f);
    }

    rx->state = next_state;

    /* Output payload symbols if synced */
    if (rx->state == SC_STATE_SYNC) {
        sc_comp phase_rot = sc_cexp(rx->phase_ambiguity);
        for (i = 0; i < SC_NPAYLOAD; i++) {
            sc_comp sym = sc_cmul(phase_rot, rx->symb_buf[fs_s + SC_NSYNC + i]);
            symbols_out[i] = rx->g * sym.real;
        }
        return 1;
    }

    return 0;
}
